sequences:
- protein:
    id: '[A]'
    sequence: MAHAGRTGYDNREIVMKYIHYKLSQRGYEWDAGDVGAAPPGAAPAPGIFSSQPGHTPHPAASRDPVARTSPLQTPAAPGAAAGPALSPVPPVVHLTLRQAGDDFSRRYRRDFAEMSSQLHLTPFTARGRFATVVEELFRDGVNWGRIVAFFEFGGVMCVESVNREMSPLVDNIALWMTEYLNRHLHTWIQDNGGWDAFVELYGPSMRPLFDFSWLSLKTLLSLALVGACITLGAYLGHK
- ligand:
    id: '[B]'
    smiles: O=C(NS(=O)(=O)c1ccccc1O)c1ccc(N2CCN(CC3CC3)CC2=O)c(O)c1
version: 1
